msg = str(input('Digite algo: '))
print(f'O tipo primitivo dele é {type(msg)}')
print(f'So tem espaços? ', msg.isspace())
print(f'É um número? ', msg.isnumeric())
print(f'É alfabetico? ', msg.isalpha())
print(f'É alfanúmerico? ', msg.isalnum())
print(f'Está em maisculas? ', msg.isupper())
print(f'Está em minuscolas? ', msg.islower())
print(f'Etá capitalizada? ', msg.istitle())
